# This CI will build i4neo-demo with the current version on several popular distributions

stages:
  - basic-talk
  - basic-demo
  - dist-chair-demo
  - dist-extra-demo


# Configuration of the i4neo-talk project
.config-talk:
  variables:
    PROJ: "i4neo-talk"
    PROJ_DIR: "${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/${PROJ}"
    PROJ_GIT: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/${PROJ}.git"

# Configuration of the i4neo-demo project
.config-demo:
  variables:
    PROJ: "i4neo-demo"
    PROJ_DIR: "${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/${PROJ}"
    PROJ_GIT: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/${PROJ}.git"


# Clone and setup the demo project (using current theme version)
.setup: &setup |
  rm -rf ${PROJ_DIR}
  git clone ${PROJ_GIT} ${PROJ_DIR}
  rmdir ${PROJ_DIR}/theme
  ln -s $(pwd) ${PROJ_DIR}/theme
  test -f /etc/os-release && source /etc/os-release && echo ${NAME:-} ${VERSION:-} || true
  rm -f *.pdf || true


# Build
.build:
  script:
    - *setup
    - make -C ${PROJ_DIR} all
    - cp ${PROJ_DIR}/*.pdf .
  artifacts:
    paths:
      - "*.pdf"
  retry: 2



# i4neo-talk using official texlive
texlive-talk:
  stage: basic-talk
  extends:
    - .config-talk
    - .build
  image: texlive/texlive

# i4neo-demo using official texlive (no pandoc, build only demo.pdf)
texlive-demo:
  stage: basic-demo
  extends:
    - .config-demo
    - .build
  image: texlive/texlive
  script:
    - *setup
    - make -C ${PROJ_DIR} demo.pdf
    - cp ${PROJ_DIR}/demo.pdf .


# i4neo-talk using our own neo docker image
neoDocker-talk:
  stage: basic-talk
  extends:
    - .config-talk
    - .build
  image: inf4/neo

# i4neo-demo using our own neo docker image
neoDocker-demo:
  stage: basic-demo
  extends:
    - .config-demo
    - .build
  image: inf4/neo


# ArchLinux rolling
archlinuxLatest:
  stage: dist-extra-demo
  extends:
    - .config-demo
    - .build
  image: archlinux:latest
  before_script:
    - pacman -Syu --noconfirm git make texlive-meta texlive-lang pandoc

# Fedora Latest
fedoraLatest:
  stage: dist-extra-demo
  extends:
    - .config-demo
    - .build
  image: fedora:latest
  before_script:
   - dnf install -y make git pandoc texlive-scheme-full latexmk


# Generic rules for debian based distributions
.debianoide:
  stage: dist-chair-demo
  extends:
    - .config-demo
    - .build
  before_script:
    - ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq && apt-get install -y -qq eatmydata && eatmydata apt-get install -y -qq make git texlive-full latexmk pandoc
  timeout: 3h

# Latest Ubuntu LTS Release
ubuntuLatest:
  extends: .debianoide
  image: ubuntu:latest

# Latest (rolling) Ubuntu Release
ubuntuRolling:
  extends: .debianoide
  image: ubuntu:rolling

# Current stable Debian Release
debianStable:
  extends: .debianoide
  image: debian:stable

# Development version of Debian
debianTesting:
  extends: .debianoide
  image: debian:testing

# Previous stable Debian Release
debianOldStable:
  extends: .debianoide
  image: debian:oldstable

